// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Load default env first, then allow production values to override.
loadEnv({ path: ".env" });
if (process.env.NODE_ENV === "production") {
  loadEnv({ path: ".env.production", override: true });
}

if (!process.env["DATABASE_URL"]) {
  throw new Error(
    "DATABASE_URL nao encontrada. Configure .env.production na VPS ou exporte a variavel antes de rodar Prisma.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
